version: '3'



services:
  db:
    image: spartakode/sqlite3:latest
    volumes:
      - ./db/:/root/db/
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db